### PR TITLE
Fixes and Changes

### LINKED ISSUE #400: Hall of Fame unavailable
Hello,

the hall of fame shows me the following requirements:

```
1 Round pliers
5 Fleece fabric
1 Cat figurine
5 Light bulb
5 Pack of nails
2 Insulating tape

benötigt Defective Wall Stufe 6
benötigt Illumination Stufe 2
Benötigt Mechanic Treuestufe 2
```

And I already build level 3 In game, but I can't mark it as done on the website. I met all the requirements, do you know why I can't check it?

### LINKED ISSUE #419: Hideout Tracker: Hall of Fame Upgrade unavailable
Hall of Fame (Level 1, I'm at Level 3 in game) cannot be marked as installed even with Illumination level 2+ set as finished and Defective Wall level 6 marked as finished. Gym marked as finished fine. Must be because it's a new addition, and something is overlooked. Either way not really a big deal, just a minor nuisance. Hall of Fame's icon image also shows an error loading, so it either doesn't exist or is mislinked; opening image in new tab leads to page that states "pages.not_found.not_found_description".

### PR DESCRIPTION
**Pull request by DysektAI**
This fixes:

[Add Hall Of Fame image icon](https://github.com/TarkovTracker/TarkovTracker/commit/695441f43f14f719b69850fed3176087e6c564bc)

[Remove Checks for station ID as its no longer broken](https://github.com/TarkovTracker/TarkovTracker/commit/ce6c9e447ee658dc8ad35e1dd97074d762afb105)

[Add percentage to the dashboard](https://github.com/TarkovTracker/TarkovTracker/commit/2c37b657634751b333e8f1cf6c4d8600ab69ca74)

[Updated dashboard headings with newest version and fixes](https://github.com/TarkovTracker/TarkovTracker/commit/79debda38a04360e91985ca4515485dbca036f62)

Resolves #419 , resolves #400 

And just some other simple adjustments and improvements I found to be helpful please let me know if anything needs to be changed

### CODE REVIEW

**Comment by DysektAI** [comment]
Preview of dashboard change implemented
image

File: tarkov-tracker/src/composables/tarkovdata.js
Comment (DysektAI) [inline tarkov-tracker/src/composables/tarkovdata.js:1]: This needs to be fixed accidentally removed check for the "Stash" setting

**Comment by DysektAI** [comment]
Hall of Fame working correctly now
image

**Review by Shebuka — APPROVED** [review]

**Review by TheOgreTV — APPROVED** [review]

**Review by TheOgreTV — APPROVED** [review]

**Comment by thaddeus** [comment]
Sorry for being very behind on reviewing PRs! I am getting things updated for the new wipe, I will try to test this in the next day or so!

File: functions/package.json [hunk 1]
```diff
@@ -12,7 +12,7 @@
   "main": "index.js",
   "dependencies": {
     "firebase-admin": "^10.3.0",
-    "firebase-functions": "^4.4.0",
+    "firebase-functions": "^4.9.0",
```
Comment (roman-bytes) [inline functions/package.json:15]: Just want to make sure, is this need/intended?

File: tarkov-tracker/package.json [hunk 2]
```diff
@@ -20,7 +20,7 @@
     "firebase": "^9.23.0",
     "firebaseui": "^6.0.1",
     "graphology": "^0.25.1",
-    "graphql": "^16.6.0",
+    "graphql": "16.6.0",
```
Comment (roman-bytes) [inline tarkov-tracker/package.json:23]: Is this on purpose as well? It's normally not a good thing to remove the ^.

File: tarkov-tracker/package.json [hunk 3]
```diff
@@ -47,7 +47,7 @@
     "sass": "^1.52.3",
     "vite": "^2.9.16",
     "vite-plugin-eslint": "^1.6.1",
-    "vite-plugin-firebase": "^0.5.0",
```
Comment (DysektAI) [inline tarkov-tracker/package.json:50]: Resolves the error and issue from #439

**Review by roman-bytes — COMMENTED** [review]
This looks good to me @thaddeus just not sure how to trigger the test action.

**Review by mjaveld — APPROVED** [review]
Overall, looks like its good 😃. I do want to make sure you saw [@roman-bytes comment](https://github.com/TarkovTracker/TarkovTracker/pull/420/files#r1844967593) that you did confirm this minor upgrade doesn't have side-effects. Anyways, I approve

**Comment by muzica9** [comment]
still can not build 

image

**Comment by DysektAI** [comment]
> still can not build. icon is missing and all requirments are build.
> 
> image

Still waiting for review and merge from @thaddeus or @roman-bytes when available its been a while now not sure if this will ever be seen at this rate.

File: tarkov-tracker/package.json (hunk 3 above)
Comment (frmjar) [reply tarkov-tracker/package.json:50]: I had the same problem as the above-mentioned incident and it has been solved with this modification.

**Review by roman-bytes — APPROVED** [review]
